program: train_eval.py
method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  learning_rate:
    distribution: uniform
    min: 1e-5
    max: 1e-3
  weight_decay:
    values: [0, 1e-5, 1e-4, 1e-3]
  grad_accum_steps:
    values: [2, 4, 8]
  num_layers:
    values: [1, 2, 3, 4]
  num_heads:
    values: [2, 4, 8]
  hidden_dim:
    values: [64, 128, 256]
  dropout_rate:
    distribution: uniform
    min: 0.0
    max: 0.5
