program: train_eval.py
method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e-2
  weight_decay:
    distribution: log_uniform_values
    min: 1e-8
    max: 1e-3
  num_layers:
    values: [2, 4]
  num_heads:
    values: [2, 4]
  hidden_dim:
    values: [64, 128]
  dropout_rate:
    distribution: uniform
    min: 0.0
    max: 0.5
early_terminate:
  type: hyperband
  min_iter: 3 
